/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author morel
 */
//import server.ors.core.OrderRouting;
//import server.ors.ui.MessageTableModel;
package server.ors.ui;

import java.io.File;
import javax.swing.*;
import javax.swing.table.TableModel;

import server.ors.connector.ConnectToExchange;
import server.ors.core.OrderRouting;


public class OrderRoutingFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderRoutingFrame
     */
    private static OrderRouting orderrouting;

    public OrderRoutingFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {e.printStackTrace();}
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new javax.swing.JPanel();
        messageScrollPane = new javax.swing.JScrollPane();
        messageTable = new javax.swing.JTable();
        messageDetailPanel = new javax.swing.JPanel();
        messageDetailScrollPane = new javax.swing.JScrollPane();
        messageDetailTable = new javax.swing.JTable();
        RoutingHistoryPanel = new javax.swing.JPanel();
        RoutingHistoryScrollPane = new javax.swing.JScrollPane();
        RoutingHistoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OrderRoutingSystem");
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("OrderRoutingFrame"); // NOI18N
        setResizable(true);

        //messagePanel.setName("messagePanel"); // NOI18N

        messagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Application Messages"));

        messageTable.setAutoCreateRowSorter(true);
        messageTable.setModel(new server.ors.ui.MessageTableModel());
        messageTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < messageTable.getColumnCount(); i++){
            if (i==0)
                messageTable.getColumnModel().
                        getColumn(i).setPreferredWidth(30);
            if (i==1)
                messageTable.getColumnModel().
                        getColumn(i).setPreferredWidth(75);
            if (i==2)
                messageTable.getColumnModel().
                        getColumn(i).setPreferredWidth(150);
            if (i==3)
                messageTable.getColumnModel().
                        getColumn(i).setPreferredWidth(150);
            if (i==4)
                messageTable.getColumnModel().
                        getColumn(i).setPreferredWidth(800);
        }

        messageScrollPane.setViewportView(messageTable);

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageScrollPane)
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
//

        //
        messageDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Message Details"));

        messageDetailTable.setAutoCreateRowSorter(true);
        messageDetailTable.setModel(new server.ors.ui.MessageDetailTableModel(messageTable));
        messageDetailTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < messageDetailTable.getColumnCount(); i++){
            if (i==0)
                messageDetailTable.getColumnModel().
                        getColumn(i).setPreferredWidth(100);
            if (i==1)
                messageDetailTable.getColumnModel().
                        getColumn(i).setPreferredWidth(40);
            if (i==2)
                messageDetailTable.getColumnModel().
                        getColumn(i).setPreferredWidth(150);
            if (i==3)
                messageDetailTable.getColumnModel().
                        getColumn(i).setPreferredWidth(150);
        }
        messageDetailScrollPane.setViewportView(messageDetailTable);

        javax.swing.GroupLayout messageDetailPanelLayout = new javax.swing.GroupLayout(messageDetailPanel);
        messageDetailPanel.setLayout(messageDetailPanelLayout);
        messageDetailPanelLayout.setHorizontalGroup(
                messageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(messageDetailScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        messageDetailPanelLayout.setVerticalGroup(
                messageDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messageDetailPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messageDetailScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );


        RoutingHistoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Routing History"));

        RoutingHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RoutingHistoryScrollPane.setViewportView(RoutingHistoryTable);

        javax.swing.GroupLayout RoutingHistoryPanelLayout = new javax.swing.GroupLayout(RoutingHistoryPanel);
        RoutingHistoryPanel.setLayout(RoutingHistoryPanelLayout);
        RoutingHistoryPanelLayout.setHorizontalGroup(
            RoutingHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoutingHistoryPanelLayout.createSequentialGroup()
                .addComponent(RoutingHistoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        RoutingHistoryPanelLayout.setVerticalGroup(
            RoutingHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoutingHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RoutingHistoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RoutingHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(messageDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoutingHistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderRoutingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderRoutingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderRoutingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderRoutingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                orderrouting = new OrderRouting();
                orderrouting.start();
                new OrderRoutingFrame().setVisible(true);
            }

        });
//        try {
//            ConnectToExchange.main(args);
//        } catch (Exception e) {
//            System.out.println(e);
//        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RoutingHistoryPanel;
    private javax.swing.JScrollPane RoutingHistoryScrollPane;
    private javax.swing.JTable RoutingHistoryTable;
    private javax.swing.JPanel messageDetailPanel;
    private javax.swing.JScrollPane messageDetailScrollPane;
    private javax.swing.JTable messageDetailTable;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JScrollPane messageScrollPane;
    private javax.swing.JTable messageTable;
    // End of variables declaration//GEN-END:variables
}
